version: "3.3"
services:
  hello:
    image: busybox
    command:
      sh -c 'while true; do nc -lp 8000 -e echo -e "HTTP/1.1 200 OK\r\n\r\n{\"msg\":\"hello\",\"host\":\"$$HOSTNAME\"}"; done'
    ports:
      - 8000-8002:8000
